service: store-app
frameworkVersion: '4'

plugins:
  - serverless-offline
  - serverless-python-requirements

useDotenv: true

package:
  patterns:
    - "!./**"
    - "handlers/**"
    - "Classes/**"
    - "Models/**"

custom:
  serverless-offline:
    httpPort: 3003

  globalTimeOut: 30

  cors:
    origin: "*"
    headers:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
      - Access-Control-Allow-Headers
      - Accept
      - Accept-Language
      - Content-Language
      - Access-Control-Allow-Origin
      - Access-Control-Allow-Methods
      - Access-Control-Allow-Credentials

  pythonRequirements:
    fileName: requirements.txt
    layer: true
    slim: true
    strip: false
    slimPatternsAppendDefaults: false
    slimPatterns:
      - boto3/**
      - botocore/**
      - s3transfer/**
      - urllib3/**
      - mysql/vendor/**
      - '*/.py[c|o]'
      - '*/_pycache_'

provider:

  name: aws
  runtime: python3.9
  environment:
    DATABASE_USER: ${env:DATABASE_USER}
    DATABASE_PASSWORD: ${env:DATABASE_PASSWORD}
    DATABASE_NAME: ${env:DATABASE_NAME}
    DATABASE_HOST: ${env:DATABASE_HOST}
    USER_POOL: ${env:USER_POOL}
    CLIENT_ID: ${env:CLIENT_ID}
    SECRET_HASH: ${env:SECRET_HASH}
    CLOUD_NAME: ${env:CLOUD_NAME}
    API_KEY: ${env:API_KEY}
    API_SECRET: ${env:API_SECRET}

  layers:
    - Ref: PythonRequirementsLambdaLayer

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - s3:PutObject
            - s3:GetObject
            - cognito-idp:AdminSetUserPassword
            - cognito-idp:AdminUpdateUserAttributes
            - cognito-idp:GetUser
          Resource: "*"

functions:
  ProductsAPI:
    name: Products-Api
    handler: handlers/ProductsHandler.products
    timeout: ${self:custom.globalTimeOut}
    events:
      - http:
          path: /products
          method: post
          cors: ${self:custom.cors}
      - http:
          path: /products
          method: get
          cors: ${self:custom.cors}

  TypesProductsAPI:
    name: Types-Products-Api
    handler: handlers/ProductsHandler.types_products
    timeout: ${self:custom.globalTimeOut}
    events:
      - http:
          path: /types_products
          method: post
          cors: ${self:custom.cors}
      - http:
          path: /types_products
          method: get
          cors: ${self:custom.cors}
